# Generated by Django 3.1.4 on 2021-03-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CameraApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('blood_group', models.CharField(choices=[('A +ve', 'A +ve'), ('A -ve', 'A -ve'), ('B +ve', 'B +ve'), ('B -ve', 'B -ve'), ('AB +ve', 'AB +ve'), ('AB -ve', 'AB -ve'), ('O +ve', 'O +ve'), ('O -ve', 'O -ve')], default='A +ve', max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')], default='Male', max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Active', max_length=10)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(help_text='abc@example.com', max_length=50)),
                ('city', models.CharField(max_length=25, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Patient_Users')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ('id',),
            },
        ),
    ]
