# Generated by Django 3.1.4 on 2021-03-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CameraApp', '0003_patient_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contact',
            field=models.CharField(max_length=50),
        ),
    ]
