# Generated by Django 3.1.4 on 2021-03-31 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CameraApp', '0004_auto_20210330_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='photo',
        ),
    ]
