# Generated by Django 3.1.4 on 2021-03-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CameraApp', '0005_remove_patient_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
