# Generated by Django 3.1.4 on 2021-04-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Booking_time',
            field=models.CharField(choices=[('10:00 to 10:30', '10:00 to 10:30'), ('10:30 to 11:00', '10:30 to 11:00'), ('11:00 to 11:30', '11:00 to 11:30'), ('11:30 to 12:00', '11:30 to 12:00'), ('12:00 to 12:30', '12:00 to 12:30'), ('12:30 to 01:00', '12:30 to 01:00'), ('18:00 to 18:30', '18:00 to 18:30'), ('18:30 to 19:00', '18:30 to 19:00'), ('19:00 to 19:30', '19:00 to 19:30')], default='10:00 to 10:30', max_length=15),
        ),
    ]
